export type {
    XCStrings,
    StringEntry,
    StringLocalizations,
    LocalizationEntry,
    StringUnit,
    LocalizationState,
    PluralForm,
    TranslationInput,
    TranslationData,
    KeyTranslation,
    KeyTranslationsResult,
    MissingTranslationResult,
    StaleKeyResult,
} from 'string-catalog-cli';
